const texts = [
  "Checking with shadow government",
  "Making poll in Florida",
  "Hacking the mainframe",
  "Asking ChatGPT",
  "Asking Joe Rogan",
  "Creating post on r/AskReddit",
  "Checking 2020 election results",
  "Calling the FBI",
  "Calling the CIA",
  "Looking in your browsing history",
  "Reaching the Amazon uncontacted tribes",
  "Asking the lizard people",
  "Asking the Illuminati",
  "Looking in your folders named 'homework'",
  "Watching 'Ancient Aliens' on History Channel",
  "Analyzing conspiracy theories",
  "Decrypting classified documents",
  "Infiltrating secret societies",
  "Tracking UFO sightings",
  "Contacting Area 51 insiders",
  "Consulting with the Men in Black",
  "Cracking secret codes",
  "Examining crop circles",
  "Searching for Bigfoot",
  "Contacting the ghost of Nikola Tesla",
  "Interrogating time travelers",
  "Examining secret government experiments",
  "Searching for the Loch Ness Monster",
  "Decrypting ancient manuscripts",
  "Probing the Bermuda Triangle mystery",
  "Analyzing secret society symbols",
  "Searching for hidden messages in popular songs",
  "Debunking moon landing conspiracies",
  "Exploring the Hollow Earth theory",
  "Intercepting encrypted messages",
  "Uncovering hidden government facilities",
  "Studying ancient astronaut theories",
  "Examining secret mind control experiments",
  "Decrypting alien languages",
  "Investigating parallel universes",
  "Analyzing ancient prophecies",
  "Exploring the theory of reptilian shapeshifters",
  "Contacting interdimensional beings",
  "Uncovering hidden Illuminati symbols",
  "Decoding ancient hieroglyphs",
  "Analyzing secret space missions",
  "Consulting with remote viewers",
  "Cracking the Da Vinci Code",
  "Searching for lost civilizations",
  "Examining secret Nazi experiments",
  "Infiltrating secret cults",
  "Contacting the ghost of Albert Einstein",
  "Analyzing secret society rituals",
  "Debunking chemtrail theories",
  "Intercepting government communications",
  "Exploring the mystery of the Mary Celeste",
  "Decrypting ancient Mayan calendars",
  "Investigating the curse of the pharaohs",
  "Analyzing secret messages in art",
  "Uncovering hidden Atlantis",
  "Studying the mystery of the Voynich manuscript",
  "Examining secret mind control techniques",
  "Decrypting extraterrestrial hieroglyphs",
  "Investigating time slips",
  "Analyzing ancient cave paintings",
  "Exploring the theory of ancient aliens",
  "Contacting interdimensional time travelers",
  "Uncovering hidden Masonic symbols",
  "Decoding ancient Sumerian texts",
  "Analyzing secret underwater bases",
  "Consulting with psychic mediums",
  "Cracking the enigma code",
  "Searching for evidence of time travel",
  "Examining secret government cover-ups",
  "Infiltrating secret societies within secret societies",
  "Contacting the ghost of Isaac Newton",
  "Analyzing secret society handshakes",
  "Debunking flat Earth theories",
  "Intercepting alien transmissions",
  "Exploring the mystery of the Bermuda Triangle",
  "Decrypting ancient Egyptian hieroglyphs",
  "Investigating the lost city of Atlantis",
  "Analyzing secret messages in literature",
  "Uncovering hidden government conspiracies",
  "Studying the mystery of the Roswell incident",
  "Examining secret mind manipulation techniques",
  "Decrypting extraterrestrial languages",
  "Investigating wormholes",
  "Analyzing ancient stone circles",
  "Exploring the theory of time loops",
  "Contacting interdimensional beings through Ouija boards",
  "Uncovering hidden Templar symbols",
  "Decoding ancient Greek myths",
  "Analyzing secret space stations",
  "Consulting with paranormal investigators",
  "Cracking the Zodiac killer's code",
  "Searching for evidence of parallel universes",
  "Examining secret government experiments on animals",
  "Infiltrating secret societies disguised as knitting clubs",
  "Contacting the ghost of Leonardo da Vinci",
  "Analyzing secret society initiation ceremonies",
  "Debunking reptilian conspiracy theories",
  "Intercepting secret alien signals",
  "Exploring the mystery of the Nazca lines",
  "Decrypting ancient Aztec hieroglyphs",
  "Investigating the curse of King Tutankhamun",
  "Analyzing secret messages in music",
  "Uncovering hidden time travel experiments",
  "Studying the mystery of the Bermuda Triangle disappearances",
  "Examining secret mind reading techniques",
  "Decrypting extraterrestrial codes",
  "Investigating parallel dimensions",
  "Analyzing ancient cave engravings",
  "Exploring the theory of ancient astronauts visiting Earth",
  "Contacting interdimensional beings through séances",
  "Uncovering hidden secret society symbols in corporate logos",
  "Decoding ancient Norse runes",
  "Analyzing secret underground cities",
  "Consulting with ghost hunters",
  "Cracking the Kryptos sculpture code",
  "Searching for evidence of alternate timelines",
  "Examining secret government research on psychic phenomena",
  "Infiltrating secret societies disguised as book clubs",
  "Contacting the ghost of Marie Curie",
  "Analyzing secret society secret hand signals",
  "Debunking lizard people theories",
  "Intercepting secret alien radio broadcasts",
  "Exploring the mystery of the Stonehenge",
  "Decrypting ancient Chinese hieroglyphs",
  "Investigating the curse of the Hope Diamond",
  "Analyzing secret messages in movies",
  "Uncovering hidden government time travel projects",
  "Studying the mystery of the disappearances in the Devil's Triangle",
  "Examining secret mind control drugs",
  "Decrypting extraterrestrial communication patterns",
  "Investigating parallel realities",
  "Analyzing ancient rock formations",
  "Exploring the theory of time dilation",
  "Contacting interdimensional beings through astral projection",
  "Uncovering hidden symbols in religious texts",
  "Decoding ancient Egyptian hieroglyphs",
  "Analyzing secret underwater civilizations",
  "Consulting with paranormal experts",
  "Cracking the Voynich manuscript code",
  "Searching for evidence of interdimensional portals",
  "Examining secret government experiments on psychic children",
  "Infiltrating secret societies disguised as cooking clubs",
  "Contacting the ghost of Stephen Hawking",
  "Analyzing secret society secret passwords",
  "Debunking hollow Earth theories",
  "Intercepting secret alien television broadcasts",
  "Exploring the mystery of the Nazca geoglyphs",
  "Decrypting ancient Indian hieroglyphs",
  "Investigating the curse of the Kennedy family",
  "Analyzing secret messages in video games",
  "Uncovering hidden government teleportation projects",
  "Studying the mystery of the lost colony of Roanoke",
  "Examining secret mind control technologies",
  "Decrypting extraterrestrial mathematical formulas",
  "Investigating time travel paradoxes",
  "Analyzing ancient petroglyphs",
  "Exploring the theory of the multiverse",
  "Contacting interdimensional beings through automatic writing",
  "Uncovering hidden symbols in ancient cave paintings",
  "Decoding ancient Celtic scripts",
  "Analyzing secret space exploration missions",
  "Consulting with parapsychologists",
  "Cracking the Book of Kells code",
  "Searching for evidence of time loops",
  "Examining secret government experiments on remote viewing",
  "Infiltrating secret societies disguised as knitting circles",
  "Contacting the ghost of Carl Sagan",
  "Analyzing secret society secret rituals",
  "Debunking ancient astronaut theories",
  "Intercepting secret alien internet communications",
  "Exploring the mystery of the Easter Island statues",
  "Decrypting ancient Mesopotamian hieroglyphs",
  "Investigating the curse of the pharaohs",
  "Analyzing secret messages in architecture",
  "Uncovering hidden government teleportation facilities",
  "Studying the mystery of the Bermuda Triangle",
  "Examining secret mind control experiments on animals",
  "Decrypting extraterrestrial musical compositions",
  "Investigating time travel theories",
  "Analyzing ancient cave sculptures",
  "Exploring the theory of time manipulation",
  "Contacting interdimensional beings through meditation",
  "Uncovering hidden symbols in ancient manuscripts",
  "Decoding ancient Roman inscriptions",
  "Analyzing secret space colonization plans",
  "Consulting with ufologists",
  "Cracking the secret code of the Rosetta Stone",
  "Searching for evidence of time anomalies",
  "Examining secret government experiments on psychic phenomena",
  "Infiltrating secret societies disguised as chess clubs",
  "Contacting the ghost of Albert Einstein",
  "Analyzing secret society initiation rituals",
  "Debunking ancient civilization myths",
  "Intercepting secret alien messages in radio signals",
  "Exploring the mystery of the Great Pyramid of Giza",
  "Decrypting ancient Babylonian hieroglyphs",
  "Investigating the curse of the Black Hope Diamond",
  "Analyzing secret messages in ancient cave drawings",
  "Uncovering hidden government teleportation technology",
  "Studying the mystery of the lost city of El Dorado",
  "Examining secret mind control experiments on plants",
  "Decrypting extraterrestrial hieroglyphic languages",
  "Investigating the possibility of time travel loops",
  "Analyzing ancient rock art",
  "Exploring the theory of parallel dimensions",
  "Contacting interdimensional beings through lucid dreaming",
  "Uncovering hidden symbols in ancient temples",
  "Decoding ancient Aztec scriptures",
  "Analyzing secret space warfare programs",
  "Consulting with cryptozoologists",
  "Cracking the secret code of the Mayan calendar",
  "Searching for evidence of time slips",
  "Examining secret government experiments on telekinesis",
  "Infiltrating secret societies disguised as gardening clubs",
  "Contacting the ghost of Sir Isaac Newton",
  "Analyzing secret society secret meetings",
  "Debunking ancient mythological creatures",
  "Intercepting secret alien messages in TV broadcasts",
  "Exploring the mystery of the Stone Circle of Avebury",
  "Decrypting ancient Incan hieroglyphs",
  "Investigating the curse of the cursed Hope Diamond",
  "Analyzing secret messages in ancient cave paintings",
  "Uncovering hidden government teleportation projects",
  "Studying the mystery of the lost city of Pompeii",
  "Examining secret mind control experiments on insects",
  "Decrypting extraterrestrial symbols and icons",
  "Investigating the possibility of time travel paradoxes",
  "Analyzing ancient hieroglyphic scripts",
  "Exploring the theory of parallel universes colliding",
  "Contacting interdimensional beings through hypnosis",
  "Uncovering hidden symbols in ancient tombs",
  "Decoding ancient Chinese manuscripts",
  "Analyzing secret space colonization missions",
  "Consulting with mythologists",
  "Cracking the secret code of the Egyptian Book of the Dead",
  "Searching for evidence of time disruptions",
  "Examining secret government experiments on telepathy",
  "Infiltrating secret societies disguised as hiking clubs",
  "Contacting the ghost of Galileo Galilei",
  "Analyzing secret society secret symbols",
  "Debunking ancient lost civilization theories",
  "Intercepting secret alien messages in satellite transmissions",
  "Exploring the mystery of the Stone Circles of Senegambia",
  "Decrypting ancient Olmec hieroglyphs",
  "Investigating the curse of the cursed Egyptian artifacts",
  "Analyzing secret messages in ancient murals",
  "Uncovering hidden government teleportation research",
  "Studying the mystery of the lost city of Troy",
  "Examining secret mind control experiments on birds",
  "Decrypting extraterrestrial pictographic languages",
  "Investigating the possibility of time travel paradoxes",
  "Analyzing ancient inscriptions on stones",
  "Exploring the theory of parallel universes merging",
  "Contacting interdimensional beings through tarot readings",
  "Uncovering hidden symbols in ancient artifacts",
  "Decoding ancient Hebrew texts",
  "Analyzing secret space exploration programs",
  "Consulting with cryptozoologists",
  "Cracking the secret code of the Dead Sea Scrolls",
  "Searching for evidence of time anomalies",
  "Examining secret government experiments on precognition",
  "Infiltrating secret societies disguised as photography clubs",
  "Contacting the ghost of Nikola Tesla",
  "Analyzing secret society initiation ceremonies",
  "Debunking ancient mythological creatures",
  "Intercepting secret alien messages in internet traffic",
  "Exploring the mystery of the Nazca Lines",
  "Decrypting ancient Mayan hieroglyphs",
  "Investigating the curse of the cursed Aztec artifacts",
  "Analyzing secret messages in ancient manuscripts",
  "Uncovering hidden government teleportation experiments",
  "Studying the mystery of the lost city of Atlantis",
  "Examining secret mind control experiments on marine life",
  "Decrypting extraterrestrial mathematical equations",
  "Investigating time travel possibilities",
  "Analyzing ancient stone carvings",
  "Exploring the theory of time dilation",
  "Contacting interdimensional beings through astral travel",
  "Uncovering hidden symbols in ancient cave drawings",
  "Decoding ancient Norse legends",
  "Analyzing secret space station missions",
  "Consulting with parapsychologists",
  "Cracking the code of the Voynich manuscript",
  "Searching for evidence of time loops",
  "Examining secret government experiments on remote viewing",
  "Infiltrating secret societies disguised as stamp collecting clubs",
  "Contacting the ghost of Leonardo da Vinci",
  "Analyzing secret society secret handshakes",
  "Debunking flat Earth theories",
  "Intercepting secret alien transmissions",
  "Exploring the mystery of the Bermuda Triangle",
  "Decrypting ancient Egyptian hieroglyphs",
  "Investigating the curse of King Tutankhamun",
  "Analyzing secret messages in architecture",
  "Uncovering hidden government teleportation facilities",
  "Studying the mystery of the Roswell incident",
  "Examining secret mind manipulation techniques",
  "Decrypting extraterrestrial languages",
  "Investigating wormholes",
  "Analyzing ancient stone circles",
  "Exploring the theory of time loops",
  "Contacting interdimensional beings through Ouija boards",
  "Uncovering hidden Masonic symbols",
  "Decoding ancient Greek myths",
  "Analyzing secret space stations",
  "Consulting with paranormal investigators",
  "Cracking the Zodiac killer's code",
  "Searching for evidence of parallel universes",
  "Examining secret government experiments on psychic children",
  "Infiltrating secret societies disguised as knitting clubs",
  "Contacting the ghost of Isaac Newton",
  "Analyzing secret society handshakes",
  "Debunking reptilian conspiracy theories",
  "Intercepting secret alien signals",
  "Exploring the mystery of the Nazca lines",
  "Decrypting ancient Aztec hieroglyphs",
  "Investigating the curse of the pharaohs",
  "Analyzing secret messages in literature",
  "Uncovering hidden government conspiracies",
  "Studying the mystery of the Roswell incident",
  "Examining secret mind control techniques",
  "Decrypting extraterrestrial hieroglyphs",
  "Investigating time slips",
  "Analyzing ancient cave paintings",
  "Exploring the theory of ancient aliens",
  "Contacting interdimensional time travelers",
  "Uncovering hidden Masonic symbols",
  "Decoding ancient Greek myths",
  "Analyzing secret space stations",
  "Consulting with paranormal investigators",
  "Cracking the Zodiac killer's code",
  "Searching for evidence of parallel universes",
  "Examining secret government experiments on psychic children",
  "Infiltrating secret societies disguised as knitting clubs",
  "Contacting the ghost of Isaac Newton",
  "Analyzing secret society handshakes",
  "Debunking reptilian conspiracy theories",
  "Intercepting secret alien signals",
  "Exploring the mystery of the Nazca lines",
  "Decrypting ancient Aztec hieroglyphs",
  "Investigating the curse of the pharaohs",
];

export const getRandomText = () =>
  texts[Math.floor(Math.random() * texts.length)];
